package com.example.s3uploadservice.util;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

public class FileUtils {
    /**
     * Extract the detection results from the file generated by @recognizeObject
     *
     * @param filepath Path of the file to extract information
     * @return Results
     */
    public static List<String> extractOutput(String filepath) {
        Set<String> results = new HashSet<>();

        try {
            String fileContent = new String(Files.readAllBytes(Paths.get(filepath)), StandardCharsets.UTF_8);
            String[] lines = fileContent.split("\n");

            for (String line : lines) {
                if (line.contains(":") && line.contains("%")) {
                    results.add(line.split(":")[0]);
                }
            }
        } catch (IOException e) {
            e.printStackTrace();
        }

        return new ArrayList<>(results);
    }
}